# Generated by Django 2.1.15 on 2020-09-02 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_main_solviewdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
